version: "3.9"

services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./config/google_credentials.json:/app/config/google_credentials.json:ro
